addons-window-title = Қондырмалар
addons-browse-addons = Қондырмаларды Шолу
addons-check-for-updates = Жаңартуларды Тексеру
addons-checking = Тексеру...
addons-code = Код:
addons-config = Баптау
addons-configuration = Пішіндеме
addons-disabled = (сөндірілген)
addons-disabled2 = (сөндірілген)
addons-downloaded-fnames = { $fname } жүктелді
addons-get-addons = Қондырма алу...
addons-install-addon = Қондырманы Орнату
addons-install-addons = Қондырмаларды Орнату
addons-install-anki-addon = Anki қондырмасын орнату
addons-install-from-file = Файлдан орнату...
addons-installation-complete = Орнату аяқталды
addons-installed-names = { $name } орнатылды
addons-installed-successfully = Сәтті орнатылды
addons-invalid-code = Жарамсыз код.
addons-invalid-configuration = Жарамсыз пішіндеме:
addons-no-updates-available = Қолжетімді жаңарту жоқ.
addons-requires = ({ $val } зәру)
addons-restored-defaults = Қалпына келтірілді
addons-choose-update-window-title = Қондырмаларды Жаңарту
addons-choose-update-update-all = Бәрін Жаңарту
