qt-misc-addon-will-be-installed-when-a = Қондырма профайл ашылғанда орнатылады.
qt-misc-addons = Қондырмалар
qt-misc-all-cards-notes-and-media-for = Бұл профайлдың барлық карта, жазба мен медиасы жойылады. Жалғастырасыз ба?
qt-misc-all-cards-notes-and-media-for2 = "{ $name }" профайлының барлық карта, жазба мен медиасы жойылады. Жалғастырасыз ба?
qt-misc-anki-updatedanki-has-been-released = <h1>Anki Жаңартлды</h1>Anki { $val } жарияланды.<br><br>
qt-misc-back-side-only = Артқы Жағы Ғана
qt-misc-backing-up = Сақтық Көшірмелеу...
qt-misc-browse = Шолып көру
qt-misc-change-note-type-ctrlandn = Жазба Түрін Өзгерту (Ctrl+N)
qt-misc-check-the-files-in-the-media = Медиа каталогінің файлдарын тексеру
qt-misc-choose-deck = Колоданы Таңдау
qt-misc-choose-note-type = Жазба Түрін Таңдау
qt-misc-closing = Жабу...
qt-misc-configure-interface-language-and-options = Интерфейс тілі мен бапталымдарды пімімдеу
qt-misc-copy-to-clipboard = Буферге Көшіру
qt-misc-create-filtered-deck = Сүзілген Колода Жасау...
qt-misc-debug-console = Оңдау Консолі
qt-misc-deck-will-be-imported-when-a = Колода профайл ашылғанда импортталады.
qt-misc-empty-cards = Құр Карталар...
qt-misc-error-during-startup = Жегілеу қатесі: { $val }
qt-misc-ignore-this-update = Осы жаңартуды елемеу
qt-misc-loading = Тиеу...
qt-misc-manage = Басқару
qt-misc-manage-note-types = Жазба Түрлерін Басқару
qt-misc-name-exists = Атау онсыз да бар.
qt-misc-non-unicode-text = <non-unicode text>
qt-misc-optimizing = Оңтайландыру...
qt-misc-please-ensure-a-profile-is-open = Профайл ашық және Anki бос екеніне көз жеткізіп, қайталап көріңіз.
qt-misc-please-select-1-card = (1 карта таңдаңыз)
qt-misc-please-select-a-deck = Колоданы таңдаңыз.
qt-misc-please-use-fileimport-to-import-this = Осы файлды импорттау үшін Файл>Импорт қолданыңыз.
qt-misc-processing = Өңдеу...
qt-misc-replace-your-collection-with-an-earlier2 = Жинағыңызды { $val }-дегі бұрынғы сақтық көшірмесімен ауыстыру?
qt-misc-revert-to-backup = Сақтық көшірмеге қайтару
# please do not change the quote character, and please only change the font name if you have confirmed the new name is a valid Windows font
qt-misc-segoe-ui = "Segoe UI"
qt-misc-shift-key-was-held-down-skipping = Shift пернесі басылды. Өзүйлесу мен қондырмалар жүктеуін өткізіп жіберу.
qt-misc-shortcut-key-left-arrow = Пернелер тіркесімі: Сол Жүгірткі
qt-misc-shortcut-key-right-arrow-or-enter = Пернелер тіркесімі: Оң Жүгірткі не Enter
qt-misc-stats = Санақ
qt-misc-study-deck = Колоданы Оқу
qt-misc-sync = Үйлестіру
qt-misc-target-deck-ctrlandd = Мақсат Колода (Ctrl+D)
qt-misc-the-following-character-can-not-be = Осы таңбамы қолдануға болмайды: { $val }
qt-misc-there-must-be-at-least-one = Кем дегенде бір профайл болуы керек.
qt-misc-this-file-exists-are-you-sure = Файл онсыз да бар. Қайта жазасыз ба?
qt-misc-unexpected-response-code = Күтпеген жауап коды: { $val }
qt-misc-would-you-like-to-download-it = Оны қазір жүктейсізбе?
qt-misc-error = Қате
qt-misc-anki-is-running = Anki Онсыз Да Жегілді
qt-misc-second = { $count } секунд
qt-misc-layout-auto-enabled = Бейімді орналасу қосылды
qt-misc-layout-vertical-enabled = Тік орналасу қосылды
qt-misc-layout-horizontal-enabled = Көолденең орналасу қосылды

## deprecated- these strings will be removed in the future, and do not need
## to be translated

qt-misc-replace-your-collection-with-an-earlier = Жинағыңызды бұрынғы сақтық көшірмесімен ауыстыру?
