addons-possibly-involved = ആഡ്-ഓണുകൾ ഉൾപ്പെട്ടിരിക്കാം: { $addons }
addons-failed-to-load =
    നിങ്ങൾ ഇൻസ്റ്റാൾ ചെയ്ത ഒരു ആഡ്-ഓൺ ലോഡുചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു. പ്രശ്നങ്ങൾ നിലനിൽക്കുകയാണെങ്കിൽ, ദയവായി ഉപകരണങ്ങൾ> ആഡ്-ഓണുകൾ മെനുവിലേക്ക് പോയി ആഡ്-ഓൺ അപ്രാപ്തമാക്കുക, അല്ലെങ്കിൽ ഇല്ലാതാക്കുക.¶
    '{ $name }' ലോഡുചെയ്യുമ്പോൾ:¶
    { $traceback }
addons-window-title = ആഡ്-ഓണ്‍
addons-addon-has-no-configuration = ആഡ്-ഓണിന് കോൺഫിഗറേഷൻ ഇല്ല.
addons-addon-installation-error = ആഡ്-ഓൺ ഇൻസ്റ്റാളേഷൻ പിശക്
addons-addon-was-not-downloaded-from-ankiweb = AnkiWeb-ൽ നിന്ന് ആഡ്-ഓൺ ഡൗൺലോഡ് ചെയ്തിട്ടില്ല.
addons-browse-addons = ആഡ്-ഓണുകൾ ബ്രൗസ്സുചെയ്യുക
addons-changes-will-take-effect-when-anki = Anki പുനരാരംഭിക്കുമ്പോൾ മാറ്റങ്ങൾ പ്രാബല്യത്തിൽ വരും.
addons-check-for-updates = അപ്‌ഡേറ്റുകൾക്കായി പരിശോധിക്കുക
addons-checking = പരിശോധിക്കുന്നു...
addons-code = കോഡ്:
addons-config = കോൺഫിഗറേഷൻ
addons-configuration = കോൺഫിഗറേഷൻ
addons-corrupt-addon-file = കേടായ ആഡ്-ഓൺ ഫയൽ.
addons-disabled = (അപ്രാപ്‌തമാക്കി)
addons-disabled2 = (അപ്രാപ്‌തമാക്കി)
addons-download-complete-please-restart-anki-to = ഡൗൺലോഡ് പൂർത്തിയായി. മാറ്റങ്ങൾ പ്രയോഗിക്കാൻ Anki പുനരാരംഭിക്കുക.
addons-downloaded-fnames = { $fname } ഡൗൺലോഡുചെയ്‌തു
addons-downloading-adbd-kb02fkb = ഡൗൺലോഡുചെയ്യുന്നു { $part }/{ $total } ({ $kilobytes } KB)...
addons-error-downloading-ids-errors = ഡൗൺലോഡുചെയ്യുന്നതിൽ പിശക് <i>{ $id }</i>: { $error }
addons-error-installing-bases-errors = ഇൻസ്റ്റാളുചെയ്യുന്നതിൽ പിശക് <i>{ $base }</i>: { $error }
addons-get-addons = ആഡ്-ഓണുകൾ നേടുക ...
addons-important-as-addons-are-programs-downloaded = <b> പ്രധാനം </ b>: ആഡ്-ഓണുകൾ ഇൻറർനെറ്റിൽ നിന്ന് ഡൗൺലോഡ് ചെയ്ത പ്രോഗ്രാമുകളായതിനാൽ, അവ ക്ഷുദ്രകരമാകാൻ സാധ്യതയുണ്ട്. <b> നിങ്ങൾ വിശ്വസിക്കുന്ന ആഡ്-ഓണുകൾ മാത്രമേ നിങ്ങൾ ഇൻസ്റ്റാൾ ചെയ്യാവൂ. </ b> <br> <br> നിങ്ങൾ ഇനിപ്പറയുന്ന Anki ആഡ്-ഓൺ (കൾ) ഇൻസ്റ്റാളുചെയ്യുന്നത് തുടരണമെന്ന് ഉറപ്പാണോ? <br> <br>% (പേരുകൾ)
addons-install-addon = ആഡ്-ഓൺ ഇൻസ്റ്റാൾ ചെയ്യുക
addons-install-addons = ആഡ്-ഓൺ (കൾ) ഇൻസ്റ്റാൾ ചെയ്യുക
addons-install-anki-addon = Anki ആഡ്-ഓൺ ഇൻസ്റ്റാൾ ചെയ്യുക
addons-install-from-file = ഫയലിൽ നിന്ന് ഇൻസ്റ്റാൾ ചെയ്യുക ...
addons-installation-complete = ഇൻസ്റ്റാളേഷൻ പൂർത്തിയായി
addons-installed-names = { $name } ഇൻസ്റ്റാളുചെയ്‌തു
addons-installed-successfully = വിജയകരമായി ഇൻസ്റ്റാൾ ചെയ്തു.
addons-invalid-addon-manifest = ആഡ്-ഓൺ മാനിഫെസ്റ്റ് അസാധുവാണ്.
addons-invalid-code = തെറ്റായ കോഡ്.
addons-invalid-code-or-addon-not-available = തെറ്റായ കോഡ്, അല്ലെങ്കിൽ നിങ്ങളുടെ Anki-യുടെ പതിപ്പിനായി ആഡ്-ഓൺ ലഭ്യമല്ല.
addons-invalid-configuration = അസാധുവായ കോൺഫിഗുറേഷൻ:
addons-invalid-configuration-top-level-object-must = അസാധുവായ കോൺഫിഗറേഷൻ: ടോപ്പ് ലെവൽ ഒബ്‌ജക്റ്റ് ഒരു മാപ്പ് ആയിരിക്കണം
addons-no-updates-available = അപ്‌ഡേറ്റുകളൊന്നും ലഭ്യമല്ല.
addons-one-or-more-errors-occurred = ഒന്നോ അതിലധികമോ പിശകുകൾ സംഭവിച്ചു:
addons-packaged-anki-addon = പാക്കേജുചെയ്‌ത Anki ആഡ്-ഓൺ
addons-please-check-your-internet-connection = നിങ്ങളുടെ ഇന്റർനെറ്റ് കണക്ഷൻ പരിശോധിക്കുക.
addons-please-report-this-to-the-respective = ഇത് ബന്ധപ്പെട്ട ആഡ്-ഓൺ രചയിതാവിന് (രചയിതാക്കൾക്ക്) റിപ്പോർട്ടുചെയ്യുക.
addons-please-restart-anki-to-complete-the = <b> ഇൻസ്റ്റാളേഷൻ പൂർത്തിയാക്കാൻ ദയവായി Anki പുനരാരംഭിക്കുക. </b>
addons-please-select-a-single-addon-first = ആദ്യം ഒരൊറ്റ ആഡ്-ഓൺ തിരഞ്ഞെടുക്കുക.
addons-requires = ({ $val } ആവശ്യമാണ്)
addons-restored-defaults = സ്ഥിരസ്ഥിതികൾ പുനഃസ്‌ഥാപിച്ചു
addons-the-following-addons-are-incompatible-with = ഇനിപ്പറയുന്ന ആഡ്-ഓണുകൾ { $name }-മായി പൊരുത്തപ്പെടുന്നില്ല, അവ പ്രവർത്തനരഹിതമാക്കി: { $found }
addons-the-following-addons-have-updates-available = ഇനിപ്പറയുന്ന ആഡ്-ഓണുകളിൽ അപ്‌ഡേറ്റുകൾ ലഭ്യമാണ്. അവ ഇപ്പോൾ ഇൻസ്റ്റാൾ ചെയ്യണോ?
addons-the-following-conflicting-addons-were-disabled = ഇനിപ്പറയുന്ന വൈരുദ്ധ്യമുള്ള ആഡ്-ഓണുകൾ അപ്രാപ്തമാക്കിയിരിക്കുന്നു:
addons-this-addon-is-not-compatible-with = ഈ ആഡ്-ഓൺ നിങ്ങളുടെ Anki-യുടെ പതിപ്പുമായി പൊരുത്തപ്പെടുന്നില്ല.
addons-view-files = ഫയലുകൾ കാണുക
addons-choose-update-window-title = ആഡ്-ഓണുകൾ അപ്‌ഡേറ്റുചെയ്യുക
addons-choose-update-update-all = എല്ലാം അപ്‌ഡേറ്റുചെയ്യുക
