qt-misc-all-cards-notes-and-media-for = Mọi thẻ, phiếu và dữ liệu phương tiện cho hồ sơ này sẽ bị xóa. Bạn có chắc chắn không?
qt-misc-anki-updatedanki-has-been-released = <h1>Bản Cập nhật Anki</h1>Anki { $val } đã được phát hành.<br><br>
qt-misc-browse = Duyệt
qt-misc-change-note-type-ctrlandn = Đổi Kiểu Phiếu (Ctrl+N)
qt-misc-check-the-files-in-the-media = Kiểm tra các tập tin trong thư mục phương tiện
qt-misc-choose-deck = Chọn Bộ thẻ
qt-misc-choose-note-type = Chọn Kiểu Phiếu
qt-misc-configure-interface-language-and-options = Cấu hình ngôn ngữ và tùy chọn giao diện
qt-misc-create-filtered-deck = Tạo Bộ thẻ Lọc...
qt-misc-debug-console = Màn hình Gỡ lỗi
qt-misc-deck-will-be-imported-when-a = Bộ thẻ sẽ được nhập vào khi mở hồ sơ.
qt-misc-default = Mặc định
qt-misc-empty-cards = Thẻ Trống...
qt-misc-error-during-startup = Có lỗi trong quá trình khởi chạy: { $val }
qt-misc-filtered-deck = Bộ thẻ Lọc { $val }
qt-misc-ignore-this-update = Bỏ qua bản cập nhật này
qt-misc-in-order-to-ensure-your-collection = Để bảm đảm rằng bộ sưu tập của bnạ hoạt động đúng đắn khi chuyển thiết bị, Anki yêu cầu đồng hồ bên trong máy tính của bạn phải được đặt chính xác. Đồng hồ bên trong có thể sai ngay cả khi hệ thống của bạn hiện thời gian nội bộ chính xác.  Vui lòng đến thiết lập thời gian trên máy tính của bạn và kiểm tra các phần sau:  - Sáng/Chiều - Độ lệch giờ - Ngày, tháng, năm - Múi giờ - Tiết kiệm giờ theo mùa  Sai biệt với giờ đúng: { $val }.
qt-misc-invalid-property-found-on-card-please = Tìm thấy thuộc tính không hợp lệ trên thẻ. Vui  lòng dùng Công cụ > Kiểm tra CSDL và nếu vẫn có vấn đề, vui lòng hỏi trên trang hỗ trợ.
qt-misc-loading = Đang nạp...
qt-misc-manage = Quản lý
qt-misc-name-exists = Trùng tên đã có.
qt-misc-non-unicode-text = <văn bản không-unicode>
qt-misc-optimizing = Đang tối ưu hóa...
qt-misc-please-connect-a-microphone-and-ensure = Xin vui lòng gắn micro vào, và chắc chắn rằng những chương trình khác đang không dùng thiết bị tiếng.
qt-misc-please-ensure-a-profile-is-open = Xin vui lòng đảm bảo rằng hồ sơ đã mở và Anki đang rỗi, rồi thử lại.
qt-misc-please-select-1-card = (vui lòng chọn 1 thẻ)
qt-misc-please-select-a-deck = Xin vui lòng chọn một bộ thẻ.
qt-misc-please-use-fileimport-to-import-this = Xin vui lòng dùng Tập tin>Nhập để nhập tập tin này.
qt-misc-processing = Đang xử lý...
qt-misc-resume-now = Tiếp tục Bây giờ
qt-misc-reverted-to-state-prior-to = Phục hồi lại trạng thái trước '{ $val }'.
qt-misc-shift-key-was-held-down-skipping = Phím Shift được nhấn giữ. Bỏ qua đồng bộ tự đồng và nạp phần gắn thêm.
qt-misc-study-deck = Học Bộ thẻ...
qt-misc-target-deck-ctrlandd = Bộ thẻ Đích (Ctrl+D)
qt-misc-the-following-character-can-not-be = Không dùng được ký tự này: { $val }
qt-misc-the-requested-change-will-require-a = Thao tác thay đổi này yêu cầu tải lên toàn bộ cơ sở dữ liệu trong lần đồng bộ bộ sưu tập kế tiếp. Nếu bạn có phần ôn tập hoặc thay đổi khác trên thiết bị khác chưa được đồng bộ thì chúng sẽ bị mất. Tiếp tục chứ?
qt-misc-there-must-be-at-least-one = Phải có ít nhất một hồ sơ.
qt-misc-this-file-exists-are-you-sure = Tập tin này đã tồn tại. Bạn có chắc chắn muốn ghi đè không?
qt-misc-undo = Hoàn tác
qt-misc-undo2 = Hoàn tác { $val }
qt-misc-waiting-for-editing-to-finish = Chờ hoàn tất chỉnh sửa.
qt-misc-would-you-like-to-download-it = Bạn có muốn tải xuống ngay bây giờ không?
