addons-window-title = Нэмэлтүүд
addons-check-for-updates = Шинэчлэлт шалгах
addons-checking = Шалгаж байна...
addons-code = Код:
addons-downloaded-fnames = { $fname }-г татав
addons-get-addons = Нэмэлтүүд авах...
addons-install-addon = Нэмэлт суулгах
addons-install-addons = Нэмэлт(үүд) суулгах
addons-install-anki-addon = Anki-гийн нэмэлтүүд суулгах
addons-install-from-file = Файлаас татах
addons-installed-successfully = Амжилттай суулгав.
addons-please-check-your-internet-connection = Интернэтийн сүлжээгээ шалгана уу.
addons-view-files = Файлууд харах
addons-choose-update-update-all = Бүгдийг шинэчлэх
