qt-accel-about = &Tungkol
qt-accel-cards = &Mga Card
qt-accel-check-database = &Tingnan ang database
qt-accel-check-media = Tingnan &Media
qt-accel-edit = &I-edit
qt-accel-exit = E&xit
qt-accel-export = &I-export...
qt-accel-export-notes = &I-export ang mga note...
qt-accel-file = &File
qt-accel-filter = Fil&ter
qt-accel-find = &Hanapin
qt-accel-find-and-replace = Hanapin at Pa&litan
qt-accel-find-duplicates = Maghanap ng &duplicate...
qt-accel-go = &Pumunta
qt-accel-guide = &Gabay
qt-accel-help = &Tulong
qt-accel-import = &I-import...
qt-accel-info = &Info...
qt-accel-invert-selection = &I-invert ang selection
qt-accel-next-card = &Susunod na card
qt-accel-note = N&ote
qt-accel-notes = &Mga Note
qt-accel-preferences = &Mga Preference
qt-accel-previous-card = &Nakaraang card
