qt-misc-addon-will-be-installed-when-a = Suiteálfar an breiseán nuair a osclaítear próifíl.
qt-misc-addons = Breiseáin
qt-misc-all-cards-notes-and-media-for = Scriosfar gach cárta, nóta agus meán don phróifíil seo. An bhfuil tú cinnte?
qt-misc-anki-updatedanki-has-been-released = <h1>Anki Nuashonraithe</h1>Anki { $val } ar fáil.<br><br>
qt-misc-automatic-syncing-and-backups-have-been = Tá sioncronú uathoibríoch agus cúltacaí díchumasaithe agus ais aischuir ar siúl. Chun iad a chur ar fáil arís, dún an phróifíl nó athtosaigh Anki.
qt-misc-back-side-only = Taobh Thiar Amháin
qt-misc-backing-up = Ag cúltacú
qt-misc-browse = Brabhsáil
qt-misc-change-note-type-ctrlandn = Athraigh Cineál nóta (Ctrl+N)
qt-misc-check-the-files-in-the-media = Seiceáil na comhaid san fhillteán meán
qt-misc-choose-deck = Roghnaigh Paca
qt-misc-choose-note-type = Roghnaigh Cineál Nóta
qt-misc-closing = Ag dúnadh...
qt-misc-configure-interface-language-and-options = Cumraigh teanga agus roghanna an chomhéadain
qt-misc-copy-to-clipboard = Cóipeáil don gearrthaisce
qt-misc-create-filtered-deck = Cruthaigh paca scagtha...
qt-misc-debug-console = Consól Dífhabhtaithe
qt-misc-deck-will-be-imported-when-a = Déanfar an paca a iompórtáil nuair a osclaítear próifíl.
qt-misc-default = Réamhshocrú
qt-misc-empty-cards = Cártaí Folmha...
qt-misc-error-during-startup = Botún i rith tosú: { $val }
qt-misc-filtered-deck = Paca Scagtha { $val }
qt-misc-ignore-this-update = Déan neamhaird ar an nuashonrú seo
qt-misc-in-order-to-ensure-your-collection = Chun cinntiú go bhfeidhmíonn do chnuasach i gceart nuair a aistrítear idir ghléasanna é, teastaíonn Anki go bhfuil do chlog cruinn. D'fhéadfaí an clog a bheith míchruinn fiú má thaispeáintear an t-am ceart ar do chóras.  Teigh chuig roghanna ama ar do ríomhaire agus seiceáil:  - AM/PM  - Féithiú cloig  - Lá, mí agus bliain  - Amchrios  - Am coigilte sholas an lae  Difear ón am cruinn: { $val }.
qt-misc-invalid-property-found-on-card-please = Airí neamhbhailí ar an gcárta. Úsáid Uirlisí>Seiceáil Bunachar Sonraí, agus má fheiceann tú an fadhb arís, cuir ceist ar an suíomh tacaíochta.
qt-misc-loading = Ag lódáil...
qt-misc-manage = Bainistigh
qt-misc-manage-note-types = Bainistigh Cineálacha Nótaí
qt-misc-name-exists = Ainm ann cheana féin.
qt-misc-non-unicode-text = <téacs nach bhfuil in unicode>
qt-misc-optimizing = Ag optamú...
qt-misc-please-connect-a-microphone-and-ensure = Ceangail mícreafón, agus cinntigh nach bhfuil an gléas in úsáid ag clár eile.
qt-misc-please-ensure-a-profile-is-open = Le próifíl ar oscailt agus gan Anki a bheith róghnóthach: bain triail arís as.
qt-misc-please-select-1-card = (roghnaigh aon chárta amháin le do thoil)
qt-misc-please-select-a-deck = Roghnaigh paca.
qt-misc-please-use-fileimport-to-import-this = Úsáid Comhad>Iompórtáil chun an comhad a iompórtáil.
qt-misc-processing = Ag próiseáil...
qt-misc-replace-your-collection-with-an-earlier = Úsáid cúltacú níos sine in áit do chnuasach?
qt-misc-resume-now = Fill Ar an Staidéar
qt-misc-revert-to-backup = Fill ar chúlbhrat
qt-misc-reverted-to-state-prior-to = Fillte chuig staid roimh '{ $val }'.
qt-misc-segoe-ui = "Segoe UI"
qt-misc-shift-key-was-held-down-skipping = SHIFT brúite. Fágfar sioncronú agus breiseáin ar lár an uair seo.
qt-misc-shortcut-key-left-arrow = Cnaipe aicearra: Saighead chlé
qt-misc-shortcut-key-right-arrow-or-enter = Cnaipe aicearra: Saighead dheis nó ENTER
qt-misc-stats = Staitisticí
qt-misc-study-deck = Paca Staidéir...
qt-misc-sync = Sionc
qt-misc-target-deck-ctrlandd = Spriocphaca (Ctrl+D)
qt-misc-the-following-character-can-not-be = Ní féidir an carachtar seo a úsáid: { $val }
qt-misc-the-requested-change-will-require-a = Don athrú seo, teastóidh uaslódáil iomlán de do bhunachar sonraí ar an gcéad sioncronú eile. Má tá athbhreithnithe nó athruithe eile ar ghléas eile nár sioncronú fós, caillfear iad. Lean ar aghaidh?
qt-misc-there-must-be-at-least-one = Teastaíon próifíl amháin ar a laghad.
qt-misc-this-file-exists-are-you-sure = Tá an comhad seo ann cheanna, agus forscríobhfar é. Cinnte?
qt-misc-unable-to-access-anki-media-folder = Níl riocht ar fillteán meáin Anki. Seiceáil na ceadanna ar an bhfillteán sealadach ar do ríomhaire.
qt-misc-unable-to-move-existing-file-to = Ní féidir an comhad a aistriú gon bhruscar - atosaigh an ríomhaire.
qt-misc-undo = Cealaigh
qt-misc-undo2 = Cealaigh { $val }
qt-misc-unexpected-response-code = Cód freagra mí-oiriúnach: { $val }
qt-misc-waiting-for-editing-to-finish = Ag fanacht ar eagarthóireacht
qt-misc-would-you-like-to-download-it = Íoslódáil anois?
qt-misc-your-collection-file-appears-to-be = Tá comhad an chnuasaigh truaillithe. Tig leis seo a tharlú nuair a chóipeáiltear (nó a bhogtar) an comhad agus Anki ar oscailt, nó nuair atá an cnuasamh lonnaithe ar thiomántán líonra nó ar néalthiomántán. Má tá an fadhb seo fós ann tar éis an ríomhaire a atosnú, oscail cúltacú uathoibríoch ón bhfuinneog phróifíl.
qt-misc-your-computers-storage-may-be-full = An bhfuil an stóras lán ar an ríomhaire? Déan spás agus bain triail eile as.
qt-misc-your-firewall-or-antivirus-program-is = Tá balla dóiteáin nó clár frithvíreas ag cur bac ar Anki ó nasc a dhéanamh leis féin. Cruthaigh eisceacht do Anki.
