addons-possibly-involved = Τα πρόσθετα που πιθανόν εμπλέκονται: { $addons }
addons-startup-failed = Η εκκίνηση του πρόσθετου απέτυχε
addons-window-title = Πρόσθετα
addons-addon-installation-error = Σφάλμα εγκατάστασης πρόσθετου
addons-changes-will-take-effect-when-anki = Οι αλλαγές θα εφαρμοστούν μετά από επανεκκίνηση του Anki.
addons-check-for-updates = Έλεγχος για ενημερώσεις
addons-checking = Έλεγχος...
addons-code = Κωδικός:
addons-corrupt-addon-file = Κατεστραμμένο αρχείο πρόσθετου.
addons-download-complete-please-restart-anki-to = Η λήψη ολοκληρώθηκε. Παρακαλώ κάνετε επανεκκίνηση του Anki για την εφαρμογή των αλλαγών.
addons-error-downloading-ids-errors = Σφάλμα λήψης <i>{ $id }</i>: { $error }
addons-error-installing-bases-errors = Σφάλμα εγκατάστασης <i>{ $base }</i>: { $error }
addons-get-addons = Λήψη πρόσθετων
addons-install-addon = Εγκατάσταση Πρόσθετου
addons-install-addons = Εγκατάσταση πρόσθετου/ων
addons-install-anki-addon = Εγκατάσταση πρόσθετου Anki
addons-install-from-file = Εγκατάσταση από αρχείο...
addons-installation-complete = Η εγκατάσταση ολοκληρώθηκε
addons-installed-successfully = Εγκαταστάθηκε επιτυχώς.
addons-invalid-code = Μη έγκυρος κώδικας.
addons-invalid-code-or-addon-not-available = Μη έγκυρος κώδικας ή το πρόσθετο δεν διατίθεται για την έκδοση του Anki που χρησιμοποιείτε.
addons-invalid-configuration = Μη έγκυρη ρύθμιση:
addons-no-updates-available = Καμία διαθέσιμη ενημέρωση.
addons-one-or-more-errors-occurred = Προέκυψαν ένα ή περισσότερα σφάλματα:
addons-please-check-your-internet-connection = Παρακαλώ ελέγξτε τη σύνδεση σας στο διαδίκτυο.
addons-please-report-this-to-the-respective = Παρακαλούμε κάνετε αναφορά στον συγγραφέα/είς του πρόσθετου.
addons-please-restart-anki-to-complete-the = <b>Παρακαλώ κάνετε επανεκκίνηση του Anki για την ολοκλήρωση της εγκατάστασης.</b>
addons-please-select-a-single-addon-first = Παρακαλούμε επιλέξτε πρώτα ένα πρόσθετο
addons-requires = (απαιτεί { $val })
addons-restored-defaults = Επαναφορά προεπιλογών
addons-the-following-addons-are-incompatible-with = Τα παρακάτω πρόσθετα δεν είναι συμβατά με { $name } και έχουν απενεργοποιηθεί: { $found }
addons-the-following-addons-have-updates-available = Τα ακόλουθα πρόσθετα έχουν διαθέσιμες ενημερώσεις. Εγκατάσταση τους τώρα;
addons-this-addon-is-not-compatible-with = Αυτό το πρόσθετο δεν είναι συμβατό με αυτή την έκδοση Anki.
addons-unknown-error = Άγνωστο σφάλμα: { $val }
