qt-accel-about = &וועגן
qt-accel-about-mac = וועגן „אַנקי״…
qt-accel-cards = &קאַרטלעך
qt-accel-check-database = &באַטראַכטן דאַטן-באַזע
qt-accel-check-media = באַטראַכטן &מעדיע
qt-accel-edit = &בײַטן
qt-accel-exit = אַ&רויס
qt-accel-export = &אַרויספֿירן…
qt-accel-export-notes = &אַרויספֿירן נאָטיצן
qt-accel-file = &טעקע
qt-accel-filter = פֿיל&טרירן
qt-accel-find = &זוכן
qt-accel-find-and-replace = זוכן און פֿאַר&בײַטן…
qt-accel-find-duplicates = זוכן &דופּליקאַטן…
qt-accel-go = &גיין
qt-accel-guide = &וועגווײַזער
qt-accel-help = &הילף
qt-accel-import = &אַרײַנפֿירן…
qt-accel-info = &ידיעות…
qt-accel-preferences = &אויסוואַלן
qt-accel-layout = &אויסשטעל
qt-accel-layout-auto = &אויטאָ
qt-accel-layout-vertical = &ווערטיקאַל
qt-accel-layout-horizontal = &האָריזאָנטאַל
qt-accel-toggle-sidebar = איבערשליסן זײַט-קעסטל
qt-accel-create-backup = שאַפֿן &רעזערוו-קאָפּיע
qt-accel-load-backup = &צוריקציִען אין אַ רעזערוו-קאָפּיע
qt-accel-upgrade-downgrade = פֿאָרויסרוקן / צוריקרוקן אַנקי-נוסח
