qt-accel-about = &Quant a...
qt-accel-cards = &Targetes
qt-accel-check-database = &verificar la Base de dades
qt-accel-check-media = Comprovar &multimèdia...
qt-accel-edit = &Edita
qt-accel-exit = &Surt
qt-accel-export = &Exporta...
qt-accel-export-notes = &Exportar Notes...
qt-accel-file = &Fitxer
qt-accel-filter = Fil&trar
qt-accel-find = &Cerca
qt-accel-find-and-replace = Cerca i reemplaça...
qt-accel-find-duplicates = Cerca &duplicats...
qt-accel-go = &Vés
qt-accel-guide = &Manual...
qt-accel-help = &Ajuda
qt-accel-import = &Importa...
qt-accel-info = &Info...
qt-accel-invert-selection = &Inverteix la selecció
qt-accel-next-card = &Targeta següent
qt-accel-note = N&ota
qt-accel-notes = &Notes
qt-accel-preferences = &Preferències...
qt-accel-previous-card = Targeta &anterior
qt-accel-select-all = Selecciona-ho &tot
qt-accel-select-notes = Seleccionar &Notes
qt-accel-support-anki = &Dóna suport  a Anki...
qt-accel-switch-profile = &Canviar de perfil
qt-accel-tools = &Eines
qt-accel-undo = Desfés (&U)
qt-accel-redo = &Refés
qt-accel-set-due-date = Defineix &Data de venciment...
qt-accel-forget = Oblida (&F)
qt-accel-view = Mostra (&V)
qt-accel-full-screen = Commuta pantalla completa (&F)
qt-accel-zoom-in = Amplia (&I)
qt-accel-zoom-out = Allunya't (&O)
qt-accel-reset-zoom = &Restableix el zoom
qt-accel-zoom-editor-in = Apropa l'editor (&I)
qt-accel-zoom-editor-out = Allunya l'editor (&O)
qt-accel-create-backup = Crea una còpia de seguretat
