qt-accel-about = &Аб праграме
qt-accel-browse-and-install = А&глядзець і ўсталяваць...
qt-accel-cards = &Карткі
qt-accel-check-database = &Праверыць базу даных
qt-accel-check-media = Праверыць &медыя
qt-accel-edit = &Рэдагаваць
qt-accel-exit = &Выхад
qt-accel-export = &Экспарт...
qt-accel-export-notes = &Экспартаваць нататкі...
qt-accel-file = &Файл
qt-accel-filter = Фі&льтраваць
qt-accel-find = &Знайсці
qt-accel-find-and-replace = Знайсці і за&мяніць...
qt-accel-find-duplicates = Знайсці д&ублікаты...
qt-accel-go = &Перайсці
qt-accel-guide = Дапамо&жнік
qt-accel-help = &Даведка
qt-accel-import = &Імпартаваць...
qt-accel-info = З&весткі...
qt-accel-invert-selection = &Інвертаваць выбар
qt-accel-next-card = &Наступная картка
qt-accel-note = На&татка
qt-accel-notes = &Нататкі
qt-accel-open-addons-folder = &Адкрыць папку дадатковых кампанентаў
qt-accel-preferences = &Параметры
qt-accel-previous-card = &Папярэдняя картка
qt-accel-select-all = Выбраць &усё
qt-accel-select-notes = Выбраць &нататкі
qt-accel-support-anki = &Падтрымаць Anki
qt-accel-switch-profile = Пера&ключыць профіль
qt-accel-tools = &Інструменты
qt-accel-undo = &Адрабіць
qt-accel-redo = &Узнавіць
qt-accel-set-due-date = Задаць &тэрмін...
qt-accel-forget = &Забыць
