qt-accel-about = &Om...
qt-accel-cards = &Kort
qt-accel-check-database = &Kontrollera databas
qt-accel-check-media = Granska &media...
qt-accel-edit = &Redigera
qt-accel-exit = &Avsluta
qt-accel-export = &Exportera...
qt-accel-export-notes = &Exportera noter
qt-accel-file = &Arkiv
qt-accel-filter = Fil&trera
qt-accel-find = &Hitta
qt-accel-find-and-replace = Sök och &ersätt
qt-accel-find-duplicates = Sök &dubbletter
qt-accel-go = &Gå till
qt-accel-guide = &Guide
qt-accel-help = &Hjälp
qt-accel-import = &Importera...
qt-accel-info = &Info...
qt-accel-invert-selection = &Invertera markering
qt-accel-next-card = &Nästa kort
qt-accel-note = N&ot
qt-accel-notes = &Noter
qt-accel-preferences = &Inställningar...
qt-accel-previous-card = &Föregående kort
qt-accel-select-all = Markera &alla
qt-accel-select-notes = Välj &noter
qt-accel-support-anki = &Stöd Anki...
qt-accel-switch-profile = &Ändra Profil
qt-accel-tools = &Verktyg
qt-accel-undo = &Ångra
qt-accel-redo = &Gör om
qt-accel-set-due-date = Sätt &förfallodatum
qt-accel-forget = &Glöm
qt-accel-view = &Visa
qt-accel-full-screen = Växa &fullskärm
qt-accel-layout = &Layout
qt-accel-layout-auto = &Auto
qt-accel-layout-vertical = &Lodrät
qt-accel-layout-horizontal = &Vågrät
qt-accel-zoom-in = Zooma &in
qt-accel-zoom-out = Zooma &ut
qt-accel-reset-zoom = &Återställ zoom
qt-accel-toggle-sidebar = Växla sidopanel
qt-accel-zoom-editor-in = Zooma &in editor
qt-accel-zoom-editor-out = Zooma &ut editor
qt-accel-create-backup = Skapa &säkerhetskopia
qt-accel-load-backup = &Återställ till säkerhetskopia
