qt-misc-addons = Lisäosat
qt-misc-all-cards-notes-and-media-for = Kaikki tämän käyttäjätilin kortit, muistiinpanot ja mediatiedostot poistetaan. Oletko varma?
qt-misc-anki-updatedanki-has-been-released = <h1>Anki on päivitetty</h1>Anki { $val } on julkaistu.<br><br>
qt-misc-backing-up = Tehdään varmuuskopiota...
qt-misc-browse = Selaa
qt-misc-change-note-type-ctrlandn = Vaihda muistiinpanotyyppiä (Ctrl + N)
qt-misc-check-the-files-in-the-media = Tarkasta tiedostot mediakansiossa
qt-misc-choose-deck = Valitse pakka
qt-misc-choose-note-type = Valitse muistiinpanotyyppi
qt-misc-closing = Suljetaan...
qt-misc-configure-interface-language-and-options = Käyttöliittymän kieli ja asetukset
qt-misc-copy-to-clipboard = Kopioi leikepöydälle
qt-misc-create-filtered-deck = Luo suodatettu pakka...
qt-misc-debug-console = Vianjäljityskonsoli
qt-misc-deck-will-be-imported-when-a = Pakka tuodaan kun käyttäjätili avataan
qt-misc-default = Oletusarvo
qt-misc-empty-cards = Tyhjät kortit...
qt-misc-error-during-startup = Virhe käynnistyksessä:</ br> { $val }
qt-misc-filtered-deck = Suodatettu pakka { $val }
qt-misc-ignore-this-update = Unohda tämä päivitys
qt-misc-in-order-to-ensure-your-collection = Varmistaaksesi, että kokoelmasi toimii oikein laitteiden välillä siirryttäessä, Anki vaatii, että tietokoneesi sisäisen kellon täytyy olla oikeassa ajassa. Sisäinen kello voi olla väärässä vaikka järjestelmäsi näyttäisikin oikeaa paikallista aikaa.  Siirry tietokoneesi aika-asetuksiin ja tarkista seuraavat asiat:  - Näyttääkö 12 tunnin kello oikeaa vuorokauden aikaa (aamupäivä vai iltapäivä) - Kellon kulun oikea-aikaisuus - Päivä, kuukausi ja vuosi - Aikavyöhyke - Kesä-/talviaika  Ero oikeaan aikaan on: { $val }.
qt-misc-invalid-property-found-on-card-please = Kortista löydettiin virheellinen ominaisuus. Valitse Työkalut>Tarkista tietokanta. Jos ongelma ilmenee uudelleen, pyydä apua <a href="http://ankisrs.net/docs/help.html">tukisivulta</a>.
qt-misc-loading = Ladataan…
qt-misc-manage = Hallinta
qt-misc-name-exists = Nimi on olemassa.
qt-misc-non-unicode-text = <ei-unicode tekstiä>
qt-misc-optimizing = Optimoidaan...
qt-misc-please-connect-a-microphone-and-ensure = Yhdistä mikrofoni ja varmista, etteivät muut ohjelmat käytä audiolaitetta.
qt-misc-please-ensure-a-profile-is-open = Varmista, että käyttäjätili on auki eikä Anki ei käsittele muuta tietoa ja yritä sitten uudestaan.
qt-misc-please-select-1-card = (valitse 1 kortti)
qt-misc-please-select-a-deck = Valitse pakka
qt-misc-please-use-fileimport-to-import-this = Käytä toimintoa Tiedosto>Tuo tämän tiedoston tuontiin.
qt-misc-processing = Käsitellään...
qt-misc-resume-now = Jatka nyt
qt-misc-reverted-to-state-prior-to = Palautettu "{ $val }" edeltävään tilaan.
qt-misc-shift-key-was-held-down-skipping = Shift-näppäin oli painettuna. Ohitetaan automaattinen synkronointi ja liitännäisten lataus.
qt-misc-shortcut-key-left-arrow = Pikanäppäinyhdistelmä: Vasen nuoli
qt-misc-shortcut-key-right-arrow-or-enter = Pikanäppäinyhdistelmä: Oikea nuoli tai Enter
qt-misc-study-deck = Opiskele pakkaa...
qt-misc-target-deck-ctrlandd = Kohdepakka (Ctrl + D)
qt-misc-the-following-character-can-not-be = Seuraavaa merkkiä ei voida käyttää: { $val }
qt-misc-the-requested-change-will-require-a = Pyytämäsi muutos vaatii tietokannan täyden lähetyksen AnkiWebiin kun synkronoit kokoelmasi seuraavan kerran. Jos sinulla on kertauksia tai muita muutoksia odottamassa toisessa laitteessa, jota ei ole vielä synkronoitu tänne, nämä synkronoimattomat tiedot katoavat. Haluatko jatkaa?
qt-misc-there-must-be-at-least-one = On luotava vähintään yksi käyttäjätili.
qt-misc-this-file-exists-are-you-sure = Tiedosto on olemassa. Haluatko korvata sen?
qt-misc-undo = Kumoa
qt-misc-undo2 = Kumoa { $val }
qt-misc-waiting-for-editing-to-finish = Odotetaan että muokkaus valmistuu.
qt-misc-would-you-like-to-download-it = Haluatko ladata sen nyt?
qt-misc-second = { $count ->
    [one] { $count } sekunti
   *[other] { $count } sekuntia
  }
