addons-checking = Kontrol ediliyor...
addons-code = Kod:
addons-download-complete-please-restart-anki-to = İndirme tamamlandı. Değişiklikleri uygulamak için lütfen Anki´yi yeniden başlatınız.
addons-downloaded-fnames = { $fname } indirildi
addons-downloading-adbd-kb02fkb = İndiriliyor { $part }/{ $total } ({ $kilobytes }KB)...
addons-install-addon = Eklenti yükleyin
addons-install-addons = Eklenti(leri) yükleyin
addons-install-anki-addon = Anki eklentisi yükleyin
addons-install-from-file = Dosyadan yükle...
addons-installation-complete = Yükleme tamamlandı
addons-installed-names = { $name } yüklendi
addons-invalid-code = Hatalı kod.
addons-invalid-code-or-addon-not-available = Geçersiz kod, veya eklenti sizin Anki sürümünüz için mevcut değil.
addons-no-updates-available = Güncelleme mevcut değil.
addons-please-check-your-internet-connection = Lütfen internet bağlantınızı kontrol edin.
addons-unknown-error = Bilinmeyen hata: { $val }
addons-view-addon-page = Eklenti sayfasını görüntüleyin
addons-view-files = Dosyaları görüntüle
addons-choose-update-update-all = Tümünü güncelle
