qt-misc-all-cards-notes-and-media-for = Bu profil için bütün kartlar, notlar ve medya dosyaları silinecek. Emin misiniz?
qt-misc-anki-updatedanki-has-been-released = <h1>Anki Güncellendi</h1>Anki { $val } sürümü çıktı.<br><br>
qt-misc-browse = Aç
qt-misc-change-note-type-ctrlandn = Not Tipi Değiştir
qt-misc-check-the-files-in-the-media = Medya dizinindeki dosyaları kontrol edin
qt-misc-choose-deck = Deste Seçin
qt-misc-choose-note-type = Not Tipi Seçin
qt-misc-configure-interface-language-and-options = Dil ve seçenekler arayüzünü yapılandır
qt-misc-create-filtered-deck = Filtreli Deste Yaratın...
qt-misc-debug-console = Hata Ayıklama Konsolu
qt-misc-deck-will-be-imported-when-a = Bir oturum açıldığında deste içe aktarılacaktır.
qt-misc-default = Öntanımlı
qt-misc-empty-cards = Kartları kaldır
qt-misc-error-during-startup = Başlatılma hatası: { $val }
qt-misc-filtered-deck = Filtrelenmiş Deste { $val }
qt-misc-ignore-this-update = Bu güncelemeyi yoksay
qt-misc-invalid-property-found-on-card-please = Kartınızda geçersiz özellik bulundu. Lütfen Araçlar>Veritabanını Kontrol Et'i kullanın, ve problem tekrarlanırsa, lütfen destek sitesine sorun.
qt-misc-loading = Yükleniyor...
qt-misc-manage = Yönet
qt-misc-name-exists = Ad mevcut.
qt-misc-non-unicode-text = <unicode olmayan yazı>
qt-misc-optimizing = Optimize ediliyor...
qt-misc-please-connect-a-microphone-and-ensure = Lütfen mikrofon bağlayın ve diğer uygulamaların ses cihazını kullanmadığına emin olun.
qt-misc-please-ensure-a-profile-is-open = Lütfen bir profil açıkken ve Anki meşgul değilken sağlayın, sonra tekrar deneyin.
qt-misc-please-select-1-card = (lütfen 1 kart seçin)
qt-misc-please-select-a-deck = Lütfen bir deste seçin
qt-misc-please-use-fileimport-to-import-this = Lütfen bu dosyayı içe aktarma için Dosya>İçe Aktar'ı kullanın.
qt-misc-processing = İşleniyor...
qt-misc-resume-now = Devam et
qt-misc-reverted-to-state-prior-to = '{ $val }' öncesi duruma geri çevrildi.
qt-misc-shift-key-was-held-down-skipping = Shift tuşu basılı tutuldu. Otomatik sekronu ve eklenti yüklemesini atlanıyor.
qt-misc-shortcut-key-left-arrow = Kısayol tuşu: Sol ok
qt-misc-shortcut-key-right-arrow-or-enter = Kısayol tuşu: Sağ ok yada Enter
qt-misc-stats = İstatistikler
qt-misc-sync = Eşitle
qt-misc-target-deck-ctrlandd = Hedef Deste (Ctrl+D)
qt-misc-the-following-character-can-not-be = Aşağıdaki karakter kullanılamıyor: { $val }
qt-misc-the-requested-change-will-require-a = İstenen değişiklik, koleksiyonunuzu bir sonraki senkronize ettiğinizde veritabanının tam bir şekilde yüklenmesini gerektirir. Başka bir cihazda henüz senkronize edilmemiş bekleyen incelemeler veya diğer değişiklikleriniz varsa, bunlar kaybolacaktır. Devam et?
qt-misc-there-must-be-at-least-one = En az bir profil olmalı.
qt-misc-this-file-exists-are-you-sure = Bu dosya var. Üzerine yazmak istediğinizden emin misiniz?
qt-misc-undo = Geri al
qt-misc-undo2 = Geri al { $val }
qt-misc-waiting-for-editing-to-finish = Düzenlemenin bitmesi bekleniyor.
qt-misc-would-you-like-to-download-it = Şimdi indirmek istermisin ?
