qt-misc-addon-will-be-installed-when-a = תוסף יותקן כאשר פרופיל יפתח
qt-misc-addons = תוספים
qt-misc-all-cards-notes-and-media-for = כל הכרטיסים, הרשומות, והמדיה של פרופיל זה ימחקו. האם אתה בטוח?
qt-misc-anki-updatedanki-has-been-released = <h1>Anki התעדכן</h1>Anki { $val } שוחרר.<br><br>
qt-misc-automatic-syncing-and-backups-have-been = סנכרון וגיבוי אוטומטיים בוטלו בעת השחזור. להפעיל אותם שנית, סגור את הפרופיל או הפעל מחדש את Anki.
qt-misc-back-side-only = צד אחורי בלבד
qt-misc-backing-up = מגבה...
qt-misc-browse = דפדוף
qt-misc-change-note-type-ctrlandn = שנה סוג רשומה (Ctrl+N)
qt-misc-check-the-files-in-the-media = בדוק את הקבצים בתיקיית המדיה
qt-misc-choose-deck = בחר חפיסה
qt-misc-choose-note-type = בחר סוג רשומה
qt-misc-closing = סוגר...
qt-misc-configure-interface-language-and-options = הגדר שפת ואפשרויות ממשק
qt-misc-copy-to-clipboard = העתק ללוח
qt-misc-create-filtered-deck = צור חפיסה מסוננת...
qt-misc-debug-console = קונסולת ניפוי שגיאות
qt-misc-deck-will-be-imported-when-a = חפיסה תיובא כאשר פרופיל ייפתח.
qt-misc-default = ברירת-מחדל
qt-misc-empty-cards = כרטיסים ריקים...
qt-misc-error-during-startup = שגיאה בעת הפעלה: { $val }
qt-misc-filtered-deck = חפיסה מסוננת { $val }
qt-misc-ignore-this-update = התעלם מעדכון זה
qt-misc-in-order-to-ensure-your-collection = כדי לוודא שהמאגר שלך יעבוד כשורה כאשר יועבר בין מכשירים, Anki דורש שהשעון הפנימי של המחשב שלך יהיה מכוון. השעון הפנימי יכול לטעות אפילו אם המערכת מראה את הזמן המקומי נכון.<br><br>אנא לך אל הגדרות הזמן במחשב שלך ובדוק:<br><br>- AM/PM<br>- סטיית שעון (Clock drift)<br>- יום, חודש ושנה<br>- אזור זמן<br>- שעון קיץ<br><br>הבדל בין הזמן הנכון: { $val }.
qt-misc-invalid-property-found-on-card-please = נמצא מאפיין לא חוקי בכרטיס. נא השתמש ב- כלים->בדוק בסיס נתונים, ואם הבעיה ממשיכה פנה לאתר התמיכה.
qt-misc-loading = טוען...
qt-misc-manage = נהל
qt-misc-manage-note-types = נהל סוגי רשומות
qt-misc-name-exists = שם קיים.
qt-misc-non-unicode-text = <טקסט שאינו בפורמט unicode>
qt-misc-optimizing = ממטב...
qt-misc-please-connect-a-microphone-and-ensure = אנא חבר מיקרופון, ובנוסף וודא שתוכנות אחרות לא משתמשות במכשיר האודיו.
qt-misc-please-ensure-a-profile-is-open = נא וודא שפרופיל פתוח ושהתוכנה לא בשימוש, ונסה שנית
qt-misc-please-select-1-card = (אנא בחר כרטיס 1)
qt-misc-please-select-a-deck = בחר חפיסה.
qt-misc-please-use-fileimport-to-import-this = בחר באפשרות קובץ>ייבוא כדי לייבא את הקובץ הזה.
qt-misc-processing = מעבד...
qt-misc-replace-your-collection-with-an-earlier = להחליף את האוסף עם גיבוי מוקדם יותר?
qt-misc-resume-now = המשך כעת
qt-misc-revert-to-backup = חזור לגיבוי
qt-misc-reverted-to-state-prior-to = הוחזר למצב הקודם ל- '{ $val }'.
qt-misc-segoe-ui = "Arial"
qt-misc-shift-key-was-held-down-skipping = המקש Shift היה לחוץ. מדלג על סינכרון אוטומטי והטענת תוספים.
qt-misc-shortcut-key-left-arrow = מקש קיצור: חץ שמאלי
qt-misc-shortcut-key-right-arrow-or-enter = מקש קיצור: חץ ימני או אנטר
qt-misc-stats = סטטיסטיקה
qt-misc-study-deck = למד חפיסה...
qt-misc-sync = סינכרון
qt-misc-target-deck-ctrlandd = חפיסת יעד (Ctrl+D)
qt-misc-the-following-character-can-not-be = התו הבא לא ניתן לשימוש: { $val }
qt-misc-the-requested-change-will-require-a = השינוי המבוקש דורש העלאה מלאה של בסיס הנתונים בפעם הבאה שתסנכרן את המאגר שלך. אם יש לך סקירות או שינויים אחרים שממתינים על מכשיר אחר שעדיין לא סונכרן כאן, הם יושלכו. להמשיך?
qt-misc-there-must-be-at-least-one = מוכרח להיות לפחות פרופיל אחד.
qt-misc-this-file-exists-are-you-sure = קובץ זה קיים האם ברצונך לשכתב אותו?
qt-misc-unable-to-access-anki-media-folder = לא ניתן לגשת לתיקיית המדיה. יתכן שההרשאות של המערכת אינן מאפשרות גישה לתיקיית TEMP.
qt-misc-unable-to-move-existing-file-to = לא הצלחנו למחוק - נסה להפעיל את המחשב מחדש.
qt-misc-undo = בטל
qt-misc-undo2 = בטל { $val }
qt-misc-unexpected-response-code = תגובה לא צפויה: { $val }
qt-misc-waiting-for-editing-to-finish = ממתין לסיום עריכה.
qt-misc-would-you-like-to-download-it = האם ברצונך להוריד עכשיו?
qt-misc-your-collection-file-appears-to-be = הקובץ פגום. יתכן שהקובץ הועתק או הועבר בעוד התוכנה פעילה, או שהקובץ מאוחסן בענן. אם הבעיה ממשיכה לאחר אתחול המחשב מחדש, פתח גיבוי אוטומטי ממסך הפרופיל.
qt-misc-your-computers-storage-may-be-full = אחסון המחשב שלך מלא. מחק קבצים לא נחוצים ונסה שנית.
qt-misc-your-firewall-or-antivirus-program-is = חומת האש או האנטי-וירוס מפריעים לתוכנה לפעול. אנא הוסף חריגה עבור Anki.
qt-misc-second = { $count ->
    [one] { $count } שניה
   *[other] { $count } שניות
  }
