qt-misc-addon-will-be-installed-when-a = Pachetul va fi importat dacă un profil este deschis
qt-misc-all-cards-notes-and-media-for = Toate cartelele, notele şi fișierele multimedia pentru acest profil vor fi şterse. Eşti sigur?
qt-misc-anki-updatedanki-has-been-released = <h1>Anki actualizat</h1>Anki { $val } a fost lansat.<br><br>
qt-misc-backing-up = Se creează copia de rezervă...
qt-misc-browse = Răsfoire
qt-misc-change-note-type-ctrlandn = Schimbă tipul notei (Ctrl+N)
qt-misc-check-the-files-in-the-media = Verifică fișierele din dosarul multimedia
qt-misc-choose-deck = Alege pachet
qt-misc-choose-note-type = Alege tipul notei
qt-misc-closing = Se închide...
qt-misc-configure-interface-language-and-options = Configurează limba interfeței și alte opțiuni
qt-misc-create-filtered-deck = Creează pachet filtrat…
qt-misc-debug-console = Consolă pentru depanare
qt-misc-deck-will-be-imported-when-a = Pachetul va fi importat dacă un profil este deschis
qt-misc-default = Implicit
qt-misc-empty-cards = Carduri goale…
qt-misc-error-during-startup = Eroare în timpul pornirii aplicației: { $val }
qt-misc-filtered-deck = Pachet filtrat { $val }
qt-misc-ignore-this-update = Ignoră această actualizare
qt-misc-in-order-to-ensure-your-collection = Pentru a te asigura că, atunci când este mutată între dispozitive, colecția ta funcționează corect, Anki are nevoie de setarea corectă a ceasului intern al calculatorului tău. Ceasul intern poate fi eronat, chiar dacă sistemul afișează corect timpul local.  Te rog să  mergi la setările de timp ale calculatorului tău și să verifici următoarele:  - AM/PM - Abaterea ceasului - Ziua, luna și anul - Fusul orar - Salvările zilei  Diferența pentru corectarea timpului: { $val }.
qt-misc-invalid-property-found-on-card-please = Proprietate invalidă găsită pe card. Te rog să folosești Instrumente>Verifică baza de date și, dacă problema revine, te rog să ceri ajutor pe site-ul de suport.
qt-misc-loading = Se încarcă...
qt-misc-manage = Administrează
qt-misc-name-exists = Numele există.
qt-misc-non-unicode-text = <non-unicode text>
qt-misc-optimizing = Se optimizează...
qt-misc-please-select-1-card = (te rog să selectezi 1 card)
qt-misc-please-select-a-deck = Te rog să selectezi un pachet.
qt-misc-processing = Se procesează...
qt-misc-study-deck = Studiază pachet…
qt-misc-this-file-exists-are-you-sure = Fișierul există. Sunteți sigur(ă) că vreți să îl suprascrieți?
qt-misc-undo2 = Refă { $val }
qt-misc-would-you-like-to-download-it = Doriți să îl descărcați acum?
